# Site
name: "Kushagra Kaushal"
title: "Kushagra"
description: "ML, Data Science and Linux enthusiast"
logo: 'favicon.ico'
favicon: 'favicon.ico'
baseurl: /myblog
# google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Kushagra:
    name: Kushagra Kaushal
    display_name: Kushagra
    gravatar: e5615546cf4be74e393c62d1ae9f9d4
    email: kushagra9nov@gmail.com
    web: https://kshgrk.github.io/global 
    twitter: https://twitter.com/k_UGH_shagra
    description: "ML, Data Science and Linux enthusiast"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/
    
defaults:
    - scope:
          path: "" # an empty string here means all files in the project
          type: "posts" # previously `post` in Jekyll 2.2.
      values:
          layout: "post"
    - scope:
          path: "" # an empty string here means all files in the project
          type: "posts" # previously `post` in Jekyll 2.2.
      values:
          author: "Kushagra"
          toc: true


# Other
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            guess_lang: true
            line_numbers: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
    - changelog.md
    - LICENSE.txt
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/
    - mediumish-theme-jekyll/
    - temp/#
